pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - and:
        - "approved-reviews-by=@othc/dp"
        - "approved-reviews-by=@othc/data"
    actions:
      comment:
        message: PR was approved by the two required teams!
      merge:
        method: merge
